name = "running_on_gleam"
version = "0.1.0"

licences = ["Apache-2.0"]
description = "An example of the Shimmer library"
repository = { type = "github", user = "HarryET", repo = "running_on_gleam" }
links = [
    { title = "Sponsor", href = "https://github.com/sponsors/HarryET" }
]

[dependencies]
gleam_stdlib = "~> 0.23"
shimmer = "~> 0.0"
gleam_erlang = "~> 0.17"

[dev-dependencies]
gleeunit = "~> 0.6"
